"LOCATORS"
# IN LINK TEXT WE PASS ALL THE TEXT_NODE
#IN PARTIAL WE PASS ONLY PARTIAL TEXT
"PARTIAL_LINK_TEXT"
#DRIVE.FIND_element(BY.PARTIAL_LINK_TEXT"CHIFFON DRESS")
"LINK_TEXT"
#DRIVE.FIND_element(BY.LINK_TEXT"PRINTED CHIFFON DRESS")


